### ISSUE TITLE
[RFC Comments] View Model API

### ISSUE THREAD

**Issue by dineshtrivedi** [Lumkani/lumkani-wiki#11]
https://lumkani-vue-patterns.netlify.com/rfcs/view-model.html

**Comment by dineshtrivedi** [comment]
We have learned a lot by applying this architecture, we should expand some documentation related to tests, and "private" methods.

**Comment by ShailenNaidoo** [comment]
@dineshtrivedi

> We have learned a lot by applying this architecture, we should expand some documentation related to tests, and "private" methods. 

This is awesome! Thanks for the feedback

**Comment by ShailenNaidoo** [comment]
@dineshtrivedi

> We have learned a lot by applying this architecture, we should expand some documentation related to tests, and "private" methods. 

I think not just "private" methods but private things in general :smile:
